---
title: "Package for SDE smoothing"
author: "Pierre Gloaguen"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(comment = NA, fig.width = 8, eval = F,
  fig.height = 6, fig.align = "center"
)
```

# Loading

```{r}
rm(list = ls())
library(GrandParisPackage)
library(parallel)
library(ggplot2)
library(viridis)
```

# Simulation of a POD ruled by a SINE model

```{r simulation}
set.seed(122)
trueTheta <- pi/4; trueSigma2 <- 1;
n <- 1000; times <- seq(0, by = 1, length = n);
simulatedPOD <- SINE_simulate(trueTheta, trueSigma2, 10, times = times)
```

```{r plotProcess, echo = F, warning=FALSE}
library(extrafont)
par(family = "LM Roman 10")
ylim <- range(simulatedPOD[, 1:2])
plot(simulatedPOD[, "simulationTimes"], simulatedPOD[, "hiddenStates"], 
     xlab = "Time", ylim = ylim,  ylab = "Process value", type = "b", pch = 20,
     main = "Example of simulated SINE process")
points(simulatedPOD[, "simulationTimes"], simulatedPOD[, "observations"], 
     pch = 18, col = "blue")
legend("topleft", pch = c(20, 18), col = c("blue", "black"), cex = 2, bty = "n",
       legend = c("Observations", "Hidden state"))
```

# Plotting approximated log-likelihood

## The log-likelihood

```{r, logLikelihood, cache = T}
testedThetas <- seq(0, 2*pi, length.out = 100)
processValues <- simulatedPOD[, "hiddenStates"]
logDensities <- sapply(testedThetas, function(theta){
  mean(SINE_density(theta = theta, X = processValues, times = times, MC.size = 60, log = T))
})
```

## The gradient of the log likelihood

```{r gradientLogLikelihood, cache = T}
gradLogDensities <- sapply(testedThetas, function(theta){
  mean(SINE_logDensityGradient(theta = theta, X = processValues, times = times, MC.size = 30))
})
```

```{r plotLogLike, echo = F}
par(mfrow = c(2, 1), family = "LM Roman 10", oma = c(2, 2, 2, 0.1))
par(mar = c(0, 3, 1, 0))
plot(testedThetas, logDensities, xlab = "", xaxt = "n", ylab = "", cex.lab = 1.5)
mtext(text = c("Log-vraisemblance"), side = 2, outer = T, line = 0, at = 0.75, cex = 1.5)
mtext(text = c("Courbes estimées"), side = 3, outer = T, line = 0, at = 0.5, cex = 2)
abline(v = c(trueTheta, testedThetas[which.max(logDensities)]), 
       col = c("darkgreen", "red"), lwd = 2, lty = 1)
legend("top", col = c("darkgreen", "red"), lwd = 2, bty = "n", 
       legend = c("Vrai", "Max. de Vrais."))
par(mar = c(1, 3, 0, 0))
plot(testedThetas, gradLogDensities, xlab = "", ylab = "", cex.lab = 1.5)
mtext(text = c("Gradient"), side = 2, outer = T, line = 0, at = 0.25, cex = 1.5)
mtext(text = expression(theta), side = 1, outer = T, line = 0, at = 0.6, cex = 2)
abline(h = 0, lty = 2, lwd = 3)
abline(v = c(trueTheta, testedThetas[which.max(logDensities)]), 
       col = c("darkgreen", "red"), lwd = 2, lty = 1)
```

# Estimation

## Estimation with known $\sigma^2$
```{r estimation, cache = T}
observations <- simulatedPOD[, "observations"]
estTheta = T; estSig = F; updateOrders <- rep(T, n)
firstStep <- 0.5
nStart <- floor(n / 3)
steps <- c(rep(firstStep, nStart), firstStep * (1:(n - nStart) )^(-0.500001))
gradientSteps   <- matrix(steps , ncol = 2, nrow = n)
set.seed(122)
allRes <- mclapply(1:12, function(seed){
  set.seed(seed)
  thetaStart <- runif(1, 0, 2 * pi)
  Res <- fastTangOR(observations, times,
                    thetaModel = thetaStart, sigma2 = trueSigma2,
                    updateOrders = updateOrders, gradientSteps = gradientSteps, 
                    all = T, estimateSigma2 = F, randomWalkParam = 1)
}, mc.cores = detectCores())

theta_est <- sapply(allRes, function(x) x$Estimates[,1]) %% (2*pi)
levels <- 1:ncol(theta_est)
theta_est_gg <- do.call(rbind.data.frame,
                        lapply(levels, function(i){
                          n <- nrow(theta_est)
                          data.frame(estimate = theta_est[, i],
                                     start_point = factor(i, levels = levels))
                        }))
theta_est_gg$times <- times
```

```{r smoothEstFunction}
smoothEst <- function(vecEst, n0 = 400){
  n <- length(vecEst)
  if(n0 >= n)
    n0 <- max(1, floor(n / 10))
  output <- vecEst
  tailEst <- vecEst[(n0 + 1) : n]
  output[(n0 + 1) : n] <- cumsum(tailEst) * 1 / ((n0 + 1) : n - n0)
  output
}
```


```{r}
pointPlot <- ggplot(theta_est_gg, aes(x = times, y = estimate,
                                      color = start_point)) + 
  geom_path(size = 1) + labs(x = "Time", y = expression(hat(theta)), 
                              title = expression(Online~estimation~of~theta)) +
  scale_color_viridis(discrete = T, option = "C") +
  theme(plot.title = element_text(size = 30, hjust = 0.5), 
        legend.position = "none",
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 20))
pointPlot
```
