# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Class of partially diffusion process ruled by a SINE model
#' @name SINE_POD
#' @description POD with the unidimensional SDE sinus model dX_t = sin(X_t - theta)dt + dW_t
#' and the observation model Y_t = X_t + N(0, sigma2) 
#' @export SINE_POD
NULL

